'use client'

import Link from 'next/link'
import {PointerEvent,useEffect,useRef,useState} from 'react'

type Pt={x:number,y:number}
export default function PruebaCuerpo(){
 const camera=useRef<HTMLInputElement>(null),gallery=useRef<HTMLInputElement>(null),canvas=useRef<HTMLCanvasElement>(null)
 const [image,setImage]=useState<string|null>(null),[zoom,setZoom]=useState(100),[x,setX]=useState(50),[y,setY]=useState(50),[step,setStep]=useState<'frame'|'erase'|'done'>('frame'),[brush,setBrush]=useState(42),[drawing,setDrawing]=useState(false),[history,setHistory]=useState<ImageData[]>([]),[result,setResult]=useState<string|null>(null)
 const load=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setImage(URL.createObjectURL(f));setZoom(100);setX(50);setY(50);setStep('frame');setResult(null);setHistory([])}
 const photoStyle=image?{backgroundImage:`url(${image})`,backgroundSize:`${zoom}% auto`,backgroundPosition:`${x}% ${y}%`}:{}
 const drawCanvas=()=>{if(!image)return;const c=canvas.current;if(!c)return;const im=new Image();im.onload=()=>{const W=700,H=1050;c.width=W;c.height=H;const ctx=c.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,W,H);const scale=Math.max(W/im.width,H/im.height)*(zoom/100);const dw=im.width*scale,dh=im.height*scale;const dx=(W-dw)*(x/100),dy=(H-dh)*(y/100);ctx.drawImage(im,dx,dy,dw,dh);setHistory([])};im.src=image}
 const goErase=()=>setStep('erase')
 useEffect(()=>{if(step==='erase')drawCanvas()},[step])
 useEffect(()=>()=>{if(image)URL.revokeObjectURL(image)},[image])
 const pos=(e:PointerEvent<HTMLCanvasElement>):Pt=>{const c=e.currentTarget,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
 const eraseAt=(e:PointerEvent<HTMLCanvasElement>)=>{const c=canvas.current,ctx=c?.getContext('2d');if(!drawing||!c||!ctx)return;const p=pos(e),r=brush*c.width/c.getBoundingClientRect().width;ctx.save();ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc(p.x,p.y,r/2,0,Math.PI*2);ctx.fill();ctx.restore()}
 const start=(e:PointerEvent<HTMLCanvasElement>)=>{const c=canvas.current,ctx=c?.getContext('2d');if(!c||!ctx)return;setHistory(h=>[...h,ctx.getImageData(0,0,c.width,c.height)].slice(-15));setDrawing(true);e.currentTarget.setPointerCapture(e.pointerId);const p=pos(e),r=brush*c.width/c.getBoundingClientRect().width;ctx.save();ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc(p.x,p.y,r/2,0,Math.PI*2);ctx.fill();ctx.restore()}
 const undo=()=>{const c=canvas.current,ctx=c?.getContext('2d');if(!c||!ctx||!history.length)return;ctx.putImageData(history[history.length-1],0,0);setHistory(h=>h.slice(0,-1))}
 const reset=()=>drawCanvas()
 const save=()=>{const c=canvas.current;if(!c)return;setResult(c.toDataURL('image/png'));setStep('done')}
 return <main className="min-h-screen bg-[#f2f2f0] text-[#111] pb-10"><div className="max-w-5xl mx-auto px-4 py-6"><Link href="/dashboard/crear-album" className="text-xs text-black/45">← VOLVER AL DISEÑO</Link><h1 className="text-2xl md:text-3xl font-black mt-1">Prueba · cuerpo base</h1><p className="text-sm text-black/55 mt-1">Flujo separado: encuadre + borrador manual.</p>
 {!image?<section className="mt-5 bg-white rounded-[22px] border border-black/10 p-5 md:p-8"><h2 className="text-xl font-black">1. Subí una foto</h2><p className="text-sm text-black/55 mt-2">Primero encuadramos el cuerpo. Después borrás cabeza y cualquier zona que no quieras conservar.</p><div className="grid grid-cols-2 gap-3 mt-6"><button onClick={()=>camera.current?.click()} className="bg-black text-white rounded-2xl p-5 font-black">📷 CÁMARA</button><button onClick={()=>gallery.current?.click()} className="border-2 border-black rounded-2xl p-5 font-black">▧ CARRETE</button></div></section>:
 step==='frame'?<div className="mt-5 grid lg:grid-cols-[1fr_320px] gap-5"><section className="bg-white rounded-[22px] border border-black/10 p-4 md:p-6"><span className="text-[10px] tracking-[.18em] font-black text-black/40">PASO 2</span><h2 className="text-xl font-black">Acomodá el encuadre</h2><div className="relative mx-auto mt-4 w-full max-w-[430px] aspect-[2/3] bg-[#ddd] overflow-hidden rounded-2xl" style={photoStyle}/></section><aside className="bg-white rounded-[22px] border border-black/10 p-5 self-start"><h3 className="font-black">Ajustes</h3><label className="block mt-5 text-[11px] font-black">ZOOM · {zoom}%<input className="w-full mt-2 accent-black" type="range" min="70" max="180" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><label className="block mt-5 text-[11px] font-black">HORIZONTAL<input className="w-full mt-2 accent-black" type="range" min="0" max="100" value={x} onChange={e=>setX(+e.target.value)}/></label><label className="block mt-5 text-[11px] font-black">VERTICAL<input className="w-full mt-2 accent-black" type="range" min="0" max="100" value={y} onChange={e=>setY(+e.target.value)}/></label><button onClick={goErase} className="w-full bg-black text-white rounded-xl p-4 mt-6 text-xs font-black">LISTO, BORRAR →</button><button onClick={()=>setImage(null)} className="w-full border rounded-xl p-3 mt-2 text-xs font-black">CAMBIAR FOTO</button></aside></div>:
 <div className="mt-5 grid lg:grid-cols-[1fr_320px] gap-5"><section className="bg-white rounded-[22px] border border-black/10 p-4 md:p-6"><span className="text-[10px] tracking-[.18em] font-black text-black/40">{step==='done'?'RESULTADO':'PASO 3'}</span><h2 className="text-xl font-black">{step==='done'?'Cuerpo listo':'Pintá lo que querés borrar'}</h2><div className="mx-auto mt-4 w-full max-w-[430px] aspect-[2/3] rounded-2xl overflow-hidden relative" style={{backgroundImage:'linear-gradient(45deg,#ddd 25%,transparent 25%),linear-gradient(-45deg,#ddd 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#ddd 75%),linear-gradient(-45deg,transparent 75%,#ddd 75%)',backgroundSize:'24px 24px',backgroundPosition:'0 0,0 12px,12px -12px,-12px 0'}}>{step==='done'&&result?<img src={result} className="absolute inset-0 w-full h-full object-contain"/>:<canvas ref={canvas} className="absolute inset-0 w-full h-full touch-none cursor-crosshair" onPointerDown={start} onPointerMove={eraseAt} onPointerUp={()=>setDrawing(false)} onPointerCancel={()=>setDrawing(false)}/>}</div><p className="text-xs text-black/50 mt-3 text-center">{step==='done'?'El damero representa transparencia.':'Pasá el dedo sobre cabeza, cuello o cualquier parte que quieras eliminar.'}</p></section><aside className="bg-white rounded-[22px] border border-black/10 p-5 self-start">{step==='done'?<><h3 className="font-black">Resultado</h3><p className="text-sm text-black/55 mt-2">Este PNG conserva exactamente los píxeles que no borraste.</p><button onClick={()=>setStep('erase')} className="w-full border-2 border-black rounded-xl p-4 mt-5 text-xs font-black">VOLVER A EDITAR</button></>:<><h3 className="font-black">Borrador</h3><label className="block mt-5 text-[11px] font-black">TAMAÑO · {brush}px<input className="w-full mt-2 accent-black" type="range" min="12" max="100" value={brush} onChange={e=>setBrush(+e.target.value)}/></label><div className="grid grid-cols-2 gap-2 mt-5"><button onClick={undo} className="border rounded-xl p-3 text-xs font-black">↶ DESHACER</button><button onClick={reset} className="border rounded-xl p-3 text-xs font-black">RESTAURAR</button></div><button onClick={save} className="w-full bg-black text-white rounded-xl p-4 mt-5 text-xs font-black">GUARDAR CUERPO →</button></>}</aside></div>}
 <input ref={camera} type="file" accept="image/*" capture="environment" className="hidden" onChange={load}/><input ref={gallery} type="file" accept="image/*" className="hidden" onChange={load}/></div></main>
}
