'use client'

import Link from 'next/link'
import {PointerEvent,useEffect,useRef,useState} from 'react'

type Oval={cx:number,cy:number,rx:number,ry:number}
export default function PruebaCuerpo(){
 const camera=useRef<HTMLInputElement>(null),gallery=useRef<HTMLInputElement>(null),canvas=useRef<HTMLCanvasElement>(null)
 const [image,setImage]=useState<string|null>(null),[zoom,setZoom]=useState(100),[x,setX]=useState(50),[y,setY]=useState(50),[step,setStep]=useState<'frame'|'face'|'done'>('frame'),[oval,setOval]=useState<Oval>({cx:50,cy:22,rx:13,ry:16}),[result,setResult]=useState<string|null>(null),[busy,setBusy]=useState(false)
 const load=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setImage(URL.createObjectURL(f));setZoom(100);setX(50);setY(50);setOval({cx:50,cy:22,rx:13,ry:16});setStep('frame');setResult(null)}
 const photoStyle=image?{backgroundImage:`url(${image})`,backgroundSize:`${zoom}% auto`,backgroundPosition:`${x}% ${y}%`}:{}
 const removeBg=(data:ImageData)=>{const d=data.data,w=data.width,h=data.height;const samples:number[][]=[];const grab=(px:number,py:number)=>{const i=(py*w+px)*4;samples.push([d[i],d[i+1],d[i+2]])};for(let xx=0;xx<w;xx+=Math.max(1,Math.floor(w/30))){grab(xx,0);grab(xx,h-1)}for(let yy=0;yy<h;yy+=Math.max(1,Math.floor(h/30))){grab(0,yy);grab(w-1,yy)}const avg=[0,1,2].map(k=>samples.reduce((a,s)=>a+s[k],0)/samples.length);for(let i=0;i<d.length;i+=4){const dr=d[i]-avg[0],dg=d[i+1]-avg[1],db=d[i+2]-avg[2],dist=Math.sqrt(dr*dr+dg*dg+db*db);if(dist<48)d[i+3]=0;else if(dist<88)d[i+3]=Math.round(255*(dist-48)/40)}return data}
 const prepare=()=>{if(!image)return;setStep('face');setBusy(true)}
 useEffect(()=>{if(step!=='face'||!image)return;const timer=setTimeout(()=>{const c=canvas.current;if(!c)return;const im=new Image();im.onload=()=>{const W=700,H=1050;c.width=W;c.height=H;const ctx=c.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,W,H);const scale=Math.max(W/im.width,H/im.height)*(zoom/100),dw=im.width*scale,dh=im.height*scale,dx=(W-dw)*(x/100),dy=(H-dh)*(y/100);ctx.drawImage(im,dx,dy,dw,dh);try{ctx.putImageData(removeBg(ctx.getImageData(0,0,W,H)),0,0)}catch{}setBusy(false)};im.src=image},50);return()=>clearTimeout(timer)},[step,image])
 useEffect(()=>()=>{if(image)URL.revokeObjectURL(image)},[image])
 const moveOval=(e:PointerEvent<HTMLDivElement>)=>{if(step!=='face')return;const r=e.currentTarget.getBoundingClientRect();setOval(o=>({...o,cx:Math.max(o.rx,Math.min(100-o.rx,(e.clientX-r.left)/r.width*100)),cy:Math.max(o.ry,Math.min(100-o.ry,(e.clientY-r.top)/r.height*100))}))}
 const save=()=>{const c=canvas.current,ctx=c?.getContext('2d');if(!c||!ctx)return;ctx.save();ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.ellipse(c.width*oval.cx/100,c.height*oval.cy/100,c.width*oval.rx/100,c.height*oval.ry/100,0,0,Math.PI*2);ctx.fill();ctx.restore();setResult(c.toDataURL('image/png'));setStep('done')}
 return <main className="min-h-screen bg-[#f2f2f0] text-[#111] pb-10"><div className="max-w-5xl mx-auto px-4 py-6"><Link href="/dashboard/crear-album" className="text-xs text-black/45">← VOLVER AL DISEÑO</Link><h1 className="text-2xl md:text-3xl font-black mt-1">Prueba · cuerpo base</h1><p className="text-sm text-black/55 mt-1">La app quita el fondo. Vos solamente marcás la cara.</p>
 {!image?<section className="mt-5 bg-white rounded-[22px] border border-black/10 p-5 md:p-8"><h2 className="text-xl font-black">1. Subí una foto</h2><p className="text-sm text-black/55 mt-2">Usá una foto con buena luz y, si es posible, fondo bastante uniforme.</p><div className="grid grid-cols-2 gap-3 mt-6"><button onClick={()=>camera.current?.click()} className="bg-black text-white rounded-2xl p-5 font-black">📷 CÁMARA</button><button onClick={()=>gallery.current?.click()} className="border-2 border-black rounded-2xl p-5 font-black">▧ CARRETE</button></div></section>:
 step==='frame'?<div className="mt-5 grid lg:grid-cols-[1fr_320px] gap-5"><section className="bg-white rounded-[22px] border border-black/10 p-4 md:p-6"><span className="text-[10px] tracking-[.18em] font-black text-black/40">PASO 2</span><h2 className="text-xl font-black">Acomodá el encuadre</h2><div className="relative mx-auto mt-4 w-full max-w-[430px] aspect-[2/3] bg-[#ddd] overflow-hidden rounded-2xl" style={photoStyle}/></section><aside className="bg-white rounded-[22px] border border-black/10 p-5 self-start"><h3 className="font-black">Ajustes</h3><label className="block mt-5 text-[11px] font-black">ZOOM · {zoom}%<input className="w-full mt-2 accent-black" type="range" min="70" max="180" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><label className="block mt-5 text-[11px] font-black">HORIZONTAL<input className="w-full mt-2 accent-black" type="range" min="0" max="100" value={x} onChange={e=>setX(+e.target.value)}/></label><label className="block mt-5 text-[11px] font-black">VERTICAL<input className="w-full mt-2 accent-black" type="range" min="0" max="100" value={y} onChange={e=>setY(+e.target.value)}/></label><button onClick={prepare} className="w-full bg-black text-white rounded-xl p-4 mt-6 text-xs font-black">QUITAR FONDO →</button><button onClick={()=>setImage(null)} className="w-full border rounded-xl p-3 mt-2 text-xs font-black">CAMBIAR FOTO</button></aside></div>:
 <div className="mt-5 grid lg:grid-cols-[1fr_320px] gap-5"><section className="bg-white rounded-[22px] border border-black/10 p-4 md:p-6"><span className="text-[10px] tracking-[.18em] font-black text-black/40">{step==='done'?'RESULTADO':'PASO 3'}</span><h2 className="text-xl font-black">{step==='done'?'Cuerpo listo':'Marcá la cara'}</h2><div onPointerDown={moveOval} onPointerMove={e=>{if(e.buttons)moveOval(e)}} className="mx-auto mt-4 w-full max-w-[430px] aspect-[2/3] rounded-2xl overflow-hidden relative touch-none" style={{backgroundImage:'linear-gradient(45deg,#ddd 25%,transparent 25%),linear-gradient(-45deg,#ddd 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#ddd 75%),linear-gradient(-45deg,transparent 75%,#ddd 75%)',backgroundSize:'24px 24px',backgroundPosition:'0 0,0 12px,12px -12px,-12px 0'}}>{step==='done'&&result?<img src={result} className="absolute inset-0 w-full h-full object-contain"/>:<><canvas ref={canvas} className="absolute inset-0 w-full h-full pointer-events-none"/>{!busy&&<div className="absolute border-[3px] border-red-600 rounded-[50%] bg-red-500/10" style={{left:`${oval.cx-oval.rx}%`,top:`${oval.cy-oval.ry}%`,width:`${oval.rx*2}%`,height:`${oval.ry*2}%`}}><span className="absolute -top-7 left-1/2 -translate-x-1/2 whitespace-nowrap bg-red-600 text-white text-[9px] font-black px-2 py-1 rounded">CARA A BORRAR</span></div>}{busy&&<div className="absolute inset-0 grid place-items-center bg-white/70 font-black text-xs">QUITANDO FONDO…</div>}</>}</div><p className="text-xs text-black/50 mt-3 text-center">{step==='done'?'El damero representa transparencia.':'Arrastrá el óvalo hasta cubrir cabeza y pelo.'}</p></section><aside className="bg-white rounded-[22px] border border-black/10 p-5 self-start">{step==='done'?<><h3 className="font-black">Resultado</h3><p className="text-sm text-black/55 mt-2">Fondo y zona marcada quedaron transparentes.</p><button onClick={()=>setStep('frame')} className="w-full border-2 border-black rounded-xl p-4 mt-5 text-xs font-black">REPETIR</button></>:<><h3 className="font-black">Óvalo de cara</h3><label className="block mt-5 text-[11px] font-black">ANCHO<input className="w-full mt-2 accent-red-600" type="range" min="7" max="28" value={oval.rx} onChange={e=>setOval(o=>({...o,rx:+e.target.value}))}/></label><label className="block mt-5 text-[11px] font-black">ALTO<input className="w-full mt-2 accent-red-600" type="range" min="8" max="30" value={oval.ry} onChange={e=>setOval(o=>({...o,ry:+e.target.value}))}/></label><button disabled={busy} onClick={save} className="w-full bg-black disabled:bg-black/30 text-white rounded-xl p-4 mt-6 text-xs font-black">BORRAR CARA Y GUARDAR →</button><p className="text-[11px] text-black/45 mt-3">El fondo se detecta desde los bordes de la foto. El óvalo define exactamente la zona de cabeza que se vuelve transparente.</p></>}</aside></div>}
 <input ref={camera} type="file" accept="image/*" capture="environment" className="hidden" onChange={load}/><input ref={gallery} type="file" accept="image/*" className="hidden" onChange={load}/></div></main>
}
